#!/bin/sh
if [ "x$CASSANDRA_INCLUDE" = "x" ]; then
    for include in /usr/share/cassandra/cassandra.in.sh \
                   /usr/local/share/cassandra/cassandra.in.sh \
                   /opt/cassandra/cassandra.in.sh \
                   ~/.cassandra.in.sh \
                   "`dirname "$0"`/cassandra.in.sh"; do
        if [ -r "$include" ]; then
            . "$include"
            break
        fi
    done
elif [ -r "$CASSANDRA_INCLUDE" ]; then
    . "$CASSANDRA_INCLUDE"
fi

java -Xmx2G -cp $CLASSPATH:../aegisthus-hadoop/build/libs/aegisthus-hadoop-0.1.2.jar com.netflix.aegisthus.tools.SSTableExport $*
